<?php

/*
  
** --- CONSULTA ARQUIVOS XML NO SITE DA RECEITA --- **      
<Consulta>
    <ModeloDocumento>NFe</ModeloDocumento>
    <Versao>3.10</Versao>
    <tpAmb>2</tpAmb>
    <CnpjEmpresa>99999999999999</CnpjEmpresa>
    <CnpjEmissor>99999999999999</CnpjEmissor>
    <NumeroInicial>1</NumeroInicial>
    <NumeroFinal>10</NumeroFinal>
    <Serie>1</Serie>
    <ChaveAcesso/>
    <DataEmissaoInicial/>
    <DataEmissaoFinal/>
    <dhUF/>
    <EmitidoRecebido/>
</Consulta

** --- RETORNA CONSULTA DOS ARQUIVOS XML ENCONTRADOS --- ** 
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SOAP-ENV:Body>
        <recepcao.ExecuteResponse xmlns="InvoiCy">
            <Invoicyretorno>
                <Mensagem>
                    <MensagemItem>
                        <Codigo>0</Codigo>
                        <Descricao/>
                        <Documentos>
                            <DocumentosItem>
                                <Documento>
                                    <![CDATA[
                                        <Documento>
                                            <DocModelo>55</DocModelo>
                                            <DocNumero>6391</DocNumero>
                                            <DocSerie>324</DocSerie> 
                                            <DocChaAcesso>43140106354976000149553240000063911000001111</DocChaAcesso>
                                            <DocProtocolo>143140000062275</DocProtocolo>
                                            <DocSitCodigo>100</DocSitCodigo>
                                            <DocSitDescricao>Autorizado o uso da NF-e</DocSitDescricao>
                                            <DocX
                                            ]]>
                                            <![CDATA[
                                            ML>PABuAGYAZQBQAHIAbwBjACAAdgBlAHIAcwBhAG8APQAiADMALgAxADAAIgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwB3AHcAdwAuAHAAbwByAHQAYQBsAGYAaQBzAGMAYQBsAC4AaQBuAGYALgBiAHIALwBuAGYAZQAiAD4APABOAEYAZQAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwB3AHcAdwAuAHAAbwByAHQAYQBsAGYAaQBzAGMAYQBsAC4AaQBuAGYALgBiAHIALwBuAGYAZQAiAD4APABpAG4AZgBOAEYAZQAgAHYAZQByAHMAYQBvAD0AIgAzAC4AMQAwACIAIABJAGQAPQAiAE4ARgBlADQAMwAxADQAMAAxADAANgAzADUANAA5ADcANgAwADAAMAAxADQAOQA1ADUAMwAyADQAMAAwADAAMAAwADYAMwA5ADEAMQAwADAAMAAwADAAMQAxADEAMQAiAD4APABpAGQAZQA+ADwAYwBVAEYAPgA0ADMAPAAvAGMAVQBGAD4APABjAE4ARgA+ADAAMAAwADAAMAAxADEAMQA8AC8AYwBOAEYAPgA8AG4AYQB0AE8AcAA+AE4ARgBFACAAQwBTAFQAIAAwADAAPAAvAG4AYQB0AE8AcAA+ADwAaQBuAGQAUABhAGcAPgAwADwALwBpAG4AZABQAGEAZwA+ADwAbQBvAGQAPgA1ADUAPAAvAG0AbwBkAD4APABzAGUAcgBpAGUAPgAzADIANAA8AC8AcwBlAHIAaQBlAD4APABuAE4ARgA+ADYAMwA5ADEAPAAvAG4ATgBGAD4APABkAGgARQBtAGkAPgAyADAAMQA0AC0AMAAxAC0AMQA3AFQAMQAxADoANQAwADoAMAAwAC0AMAAyADoAMAAwADwALwBkAGgARQBtAGkAPgA8AGQAaABTAGEAaQBFAG4AdAA+ADIAMAAxADQALQAwADEALQAxADcAVAAxADEAOgA1ADAAOgAwADAALQAwADIAOgAwADAAPAAvAGQAaABTAGEAaQBFAG4AdAA+ADwAdABwAE4ARgA+ADEAPAAvAHQAcABOAEYAPgA8AGkAZABEAGUAcwB0AD4AMgA8AC8AaQBkAEQAZQBzAHQAPgA8AGMATQB1AG4ARgBHAD4ANAAzADAAOQA2ADAANQA8AC8AYwBNAHUAbgBGAEcAPgA8AHQAcABJAG0AcAA+ADEAPAAvAHQAcABJAG0AcAA+ADwAdABwAEUAbQBpAHMAPgAxADwALwB0AHAARQBtAGkAcwA+ADwAYwBEAFYAPgAxADwALwBjAEQAVgA+ADwAdABwAEEAbQBiAD4AMgA8AC8AdABwAEEAbQBiAD4APABmAGkAbgBOAEYAZQA+ADEAPAAvAGYAaQBuAE4ARgBlAD4APABpAG4AZABGAGkAbgBhAGwAPgAwADwALwBpAG4AZABGAGkAbgBhAGwAPgA8AGkAbgBkAFAAcgBlAHMAPgAwADwALwBpAG4AZABQAHIAZQBzAD4APABwAHIAbwBjAEUAbQBpAD4AMAA8AC8AcAByAG8AYwBFAG0AaQA+ADwAdgBlAHIAUAByAG8AYwA+AE0AaQBnAHIAYQB0AGUASQBuAHYAbwBpAEMAeQA8AC8AdgBlAHIAUAByAG8AYwA+ADwALwBpAGQAZQA+ADwAZQBtAGkAdAA+ADwAQwBOAFAASgA+ADAANgAzADUANAA5ADcANgAwADAAMAAxADQAOQA8AC8AQwBOAFAASgA+ADwAeABOAG8AbQBlAD4ATQBJAEcAUgBBAFQARQAgAEMATwBNAFAAQQBOAFkAIABTAEkAUwBUAEUATQBBAFMAIABEAEUAIABJAE4ARgBPAFIATQBBAEMAQQBPADwALwB4AE4AbwBtAGUAPgA8AHgARgBhAG4AdAA+AEUATQBQAFIARQBTAEEAIABEAEUAIABUAEUAUwBUAEUAPAAvAHgARgBhAG4AdAA+ADwAZQBuAGQAZQByAEUAbQBpAHQAPgA8AHgATABnAHIAPgBSAFUAQQAgAEEARwBPAFMAVABJAE4ASABPACAAQwBPAFMAVABJADwALwB4AEwAZwByAD4APABuAHIAbwA+ADEANwAwADAAPAAvAG4AcgBvAD4APAB4AEMAcABsAD4AQQBOAEQAQQBSACAAMAAyADwALwB4AEMAcABsAD4APAB4AEIAYQBpAHIAcgBvAD4AQgBBAFIAUgBBACAARABPACAASgBBAEMAQQBSAEUAPAAvAHgAQgBhAGkAcgByAG8APgA8AGMATQB1AG4APgA0ADMAMAA5ADYAMAA1ADwALwBjAE0AdQBuAD4APAB4AE0AdQBuAD4ARQBOAEMAQQBOAFQAQQBEAE8APAAvAHgATQB1AG4APgA8AFUARgA+AFIAUwA8AC8AVQBGAD4APABDAEUAUAA+ADkANQA5ADYAMAAwADAAMAA8AC8AQwBFAFAAPgA8AGMAUABhAGkAcwA+ADEAMAA1ADgAPAAvAGMAUABhAGkAcwA+ADwAeABQAGEAaQBzAD4AQgBSAEEAUwBJAEwAPAAvAHgAUABhAGkAcwA+ADwAZgBvAG4AZQA+ADUAMQAzADcANQAxADMAMwAyADIAPAAvAGYAbwBuAGUAPgA8AC8AZQBuAGQAZQByAEUAbQBpAHQAPgA8AEkARQA+ADEANAA3ADAAMAA0ADkAMgA0ADEAPAAvAEkARQA+ADwAQwBSAFQAPgAzADwALwBDAFIAVAA+ADwALwBlAG0AaQB0AD4APABkAGUAcwB0AD4APABDAE4AUABKAD4AOQA5ADkAOQA5ADkAOQA5ADAAMAAwADEAOQAxADwALwBDAE4AUABKAD4APAB4AE4AbwBtAGUAPgBOAEYALQBFACAARQBNAEkAVABJAEQAQQAgAEUATQAgAEEATQBCAEkARQBOAFQARQAgAEQARQAgAEgATwBNAE8ATABPAEcAQQBDAEEATwAgAC0AIABTAEUATQAgAFYAQQBMAE8AUgAgAEYASQBTAEMAQQBMADwALwB4AE4AbwBtAGUAPgA8AGUAbgBkAGUAcgBEAGUAcwB0AD4APAB4AEwAZwByAD4AUgBPAEQAIABCAFIAIAAwADQAMAAgAEsATQAgADYAOAA4ACAAQQBSAEUAQQAgAEUAUwBQAEUAQwBJAEEATAAgADEAMQA8AC8AeABMAGcAcgA+ADwAbgByAG8APgA2ADcAPAAvAG4AcgBvAD4APAB4AEMAcABsAD4AQwBFAE4AVABSAE8APAAvAHgAQwBwAGwAPgA8AHgAQgBhAGkAcgByAG8APgBLAEUATgBOAEUARABZADwALwB4AEIAYQBpAHIAcgBvAD4APABjAE0AdQBuAD4AMwAxADEAOAA2ADAAMQA8AC8AYwBNAHUAbgA+ADwAeABNAHUAbgA+AEMATwBOAFQAQQBHAEUATQA8AC8AeABNAHUAbgA+ADwAVQBGAD4ATQBHADwALwBVAEYAPgA8AEMARQBQAD4AMwAyADEANAA1ADkAMAAwADwALwBDAEUAUAA+ADwAYwBQAGEAaQBzAD4AMQAwADUAOAA8AC8AYwBQAGEAaQBzAD4APAB4AFAAYQBpAHMAPgBCAHIAYQBzAGkAbAA8AC8AeABQAGEAaQBzAD4APABmAG8AbgBlAD4ANQA1ADMANQA0ADgAMQAxADAANQA8AC8AZgBvAG4AZQA+ADwALwBlAG4AZABlAHIARABlAHMAdAA+ADwAaQBuAGQASQBFAEQAZQBzAHQAPgAyADwALwBpAG4AZABJAEUARABlAHMAdAA+ADwAZQBtAGEAaQBsAD4AZwBhAGkAdABlAGkAcgBvAG8AQABnAG0AYQBpAGwALgBjAG8AbQA8AC8AZQBtAGEAaQBsAD4APAAvAGQAZQBzAHQAPgA8AGEAdQB0AFgATQBMAD4APABDAE4AUABKAD4AMQAxADYANAAyADQANgA4ADAAMAAwADEAMAA0ADwALwBDAE4AUABKAD4APAAvAGEAdQB0AFgATQBMAD4APABkAGUAdAAgAG4ASQB0AGUAbQA9ACIAMQAiAD4APABwAHIAbwBkAD4APABjAFAAcgBvAGQAPgAwADAAMAAwADkAPAAvAGMAUAByAG8AZAA+ADwAYwBFAEEATgAgAC8APgA8AHgAUAByAG8AZAA+ADAAMQAgAEcATABQACAAQQBDAE8ATgBEACAARQBNACAAQgBPAFQASQBKAEEATwAgAEQARQAgADAAMgBLAEcAPAAvAHgAUAByAG8AZAA+ADwATgBDAE0APgA4ADcAMQAxADMAMAAwADAAPAAvAE4AQwBNAD4APABFAFgAVABJAFAASQA+ADgANwA8AC8ARQBYAFQASQBQAEkAPgA8AEMARgBPAFAAPgA2ADEAMAAyADwALwBDAEYATwBQAD4APAB1AEMAbwBtAD4AQgBPAFQAPAAvAHUAQwBvAG0APgA8AHEAQwBvAG0APgAxAC4AMAAwADAAMAA8AC8AcQBDAG8AbQA+ADwAdgBVAG4AQwBvAG0APgAxADAAMAAuADAAMAAwADAAMAAwADAAMAAwADAAPAAvAHYAVQBuAEMAbwBtAD4APAB2AFAAcgBvAGQAPgAxADAAMAAuADAAMAA8AC8AdgBQAHIAbwBkAD4APABjAEUAQQBOAFQAcgBpAGIAIAAvAD4APAB1AFQAcgBpAGIAPgBCAE8AVAA8AC8AdQBUAHIAaQBiAD4APABxAFQAcgBpAGIAPgAxAC4AMAAwADAAMAA8AC8AcQBUAHIAaQBiAD4APAB2AFUAbgBUAHIAaQBiAD4AMQAwADAALgAwADAAMAAwADAAMAAwADAAMAAwADwALwB2AFUAbgBUAHIAaQBiAD4APABpAG4AZABUAG8AdAA+ADEAPAAvAGkAbgBkAFQAbwB0AD4APAB4AFAAZQBkAD4AYQBiAGMAPAAvAHgAUABlAGQAPgA8AG4ASQB0AGUAbQBQAGUAZAA+ADEAMgAzADwALwBuAEkAdABlAG0AUABlAGQAPgA8AC8AcAByAG8AZAA+ADwAaQBtAHAAbwBzAHQAbwA+ADwASQBDAE0AUwA+ADwASQBDAE0AUwA0ADAAPgA8AG8AcgBpAGcAPgAwADwALwBvAHIAaQBnAD4APABDAFMAVAA+ADQAMAA8AC8AQwBTAFQAPgA8AC8ASQBDAE0AUwA0ADAAPgA8AC8ASQBDAE0AUwA+ADwAUABJAFMAPgA8AFAASQBTAE4AVAA+ADwAQwBTAFQAPgAwADcAPAAvAEMAUwBUAD4APAAvAFAASQBTAE4AVAA+ADwALwBQAEkAUwA+ADwAQwBPAEYASQBOAFMAPgA8AEMATwBGAEkATgBTAE4AVAA+ADwAQwBTAFQAPgAwADcAPAAvAEMAUwBUAD4APAAvAEMATwBGAEkATgBTAE4AVAA+ADwALwBDAE8ARgBJAE4AUwA+ADwALwBpAG0AcABvAHMAdABvAD4APABpAG4AZgBBAGQAUAByAG8AZAA+AEMATwBSACAAUABSAEEAVABBACAATQBFAFQAQQBMAEkAQwBPACAARwBBAFMATwBMAEkATgBBACwAIABDAE8ATQAgADIANgAsADUASABQACwAIAAyADkAMQAgAEMAQwAgAEMATwBNACAAMABLAE0ALAAgAFAAUgBPAEMARQBEAEUATgBDAEkAQQAgAE4AQQBDAEkATwBOAEEATAAuACAAfABDAEgAQQBTAFMASQA6ACAAOQBDADIATgBDADQAMwAxADAAQQBSADAAMwAzADIAMwA0ACAATQBPAFQATwBSACAAOgAgAE4AQwA0ADMARQAxAEEAMAAzADMAMgAzADQAIABDAEwAQQBTAFMALgBGAEkAUwBDAEEATAA6ACAAOAA3ADEAMQAzADAAMAAwACAAQwBPAEQASQBHAE8AIABSAEUATgBBAFYAQQBNADoAIAAyADcAMQAwACAATgBGAEUAOgAxADIANAA5ADMAMwAvADEAIABkAGUAOgAyADIALwAwADkALwAyADAAMAA5ADwALwBpAG4AZgBBAGQAUAByAG8AZAA+ADwALwBkAGUAdAA+ADwAdABvAHQAYQBsAD4APABJAEMATQBTAFQAbwB0AD4APAB2AEIAQwA+ADAALgAwADAAPAAvAHYAQgBDAD4APAB2AEkAQwBNAFMAPgAwAC4AMAAwADwALwB2AEkAQwBNAFMAPgA8AHYASQBDAE0AUwBEAGUAcwBvAG4APgAwAC4AMAAwADwALwB2AEkAQwBNAFMARABlAHMAbwBuAD4APAB2AEIAQwBTAFQAPgAwAC4AMAAwADwALwB2AEIAQwBTAFQAPgA8AHYAUwBUAD4AMAAuADAAMAA8AC8AdgBTAFQAPgA8AHYAUAByAG8AZAA+ADEAMAAwAC4AMAAwADwALwB2AFAAcgBvAGQAPgA8AHYARgByAGUAdABlAD4AMAAuADAAMAA8AC8AdgBGAHIAZQB0AGUAPgA8AHYAUwBlAGcAPgAwAC4AMAAwADwALwB2AFMAZQBnAD4APAB2AEQAZQBzAGMAPgAwAC4AMAAwADwALwB2AEQAZQBzAGMAPgA8AHYASQBJAD4AMAAuADAAMAA8AC8AdgBJAEkAPgA8AHYASQBQAEkAPgAwAC4AMAAwADwALwB2AEkAUABJAD4APAB2AFAASQBTAD4AMAAuADAAMAA8AC8AdgBQAEkAUwA+ADwAdgBDAE8ARgBJAE4AUwA+ADAAPAAvAHYAQwBPAEYASQBOAFMAPgA8AHYATwB1AHQAcgBvAD4AMAAuADAAMAA8AC8AdgBPAHUAdAByAG8APgA8AHYATgBGAD4AMQAwADAALgAwADAAPAAvAHYATgBGAD4APAAvAEkAQwBNAFMAVABvAHQAPgA8AC8AdABvAHQAYQBsAD4APAB0AHIAYQBuAHMAcAA+ADwAbQBvAGQARgByAGUAdABlAD4AMQA8AC8AbQBvAGQARgByAGUAdABlAD4APAAvAHQAcgBhAG4AcwBwAD4APABjAG8AYgByAD4APABmAGEAdAA+ADwAbgBGAGEAdAA+ADEAPAAvAG4ARgBhAHQAPgA8AHYATwByAGkAZwA+ADEAMAAwAC4AMAAwADwALwB2AE8AcgBpAGcAPgA8AHYARABlAHMAYwA+ADUALgAwADAAPAAvAHYARABlAHMAYwA+ADwAdgBMAGkAcQA+ADkANQAuADAAMAA8AC8AdgBMAGkAcQA+ADwALwBmAGEAdAA+ADwAZAB1AHAAPgA8AG4ARAB1AHAAPgAxADwALwBuAEQAdQBwAD4APABkAFYAZQBuAGMAPgAyADAAMQAxAC0AMAA2AC0AMgAyADwALwBkAFYAZQBuAGMAPgA8AHYARAB1AHAAPgA1AC4AMAAwADwALwB2AEQAdQBwAD4APAAvAGQAdQBwAD4APABkAHUAcAA+ADwAbgBEAHUAcAA+ADIAPAAvAG4ARAB1AHAAPgA8AGQAVgBlAG4AYwA+ADIAMAAxADEALQAwADcALQAyADMAPAAvAGQAVgBlAG4AYwA+ADwAdgBEAHUAcAA+ADUALgAwADAAPAAvAHYARAB1AHAAPgA8AC8AZAB1AHAAPgA8AGQAdQBwAD4APABuAEQAdQBwAD4AMwA8AC8AbgBEAHUAcAA+ADwAZABWAGUAbgBjAD4AMgAwADEAMQAtADAAOAAtADIANAA8AC8AZABWAGUAbgBjAD4APAB2AEQAdQBwAD4ANQAuADAAMAA8AC8AdgBEAHUAcAA+ADwALwBkAHUAcAA+ADwAZAB1AHAAPgA8AG4ARAB1AHAAPgA0ADwALwBuAEQAdQBwAD4APABkAFYAZQBuAGMAPgAyADAAMQAxAC0AMAA5AC0AMgA1ADwALwBkAFYAZQBuAGMAPgA8AHYARAB1AHAAPgA1AC4AMAAwADwALwB2AEQAdQBwAD4APAAvAGQAdQBwAD4APABkAHUAcAA+ADwAbgBEAHUAcAA+ADUAPAAvAG4ARAB1AHAAPgA8AGQAVgBlAG4AYwA+ADIAMAAxADEALQAxADAALQAyADYAPAAvAGQAVgBlAG4AYwA+ADwAdgBEAHUAcAA+ADUALgAwADAAPAAvAHYARAB1AHAAPgA8AC8AZAB1AHAAPgA8AGQAdQBwAD4APABuAEQAdQBwAD4ANgA8AC8AbgBEAHUAcAA+ADwAZABWAGUAbgBjAD4AMgAwADEAMQAtADEAMAAtADIANgA8AC8AZABWAGUAbgBjAD4APAB2AEQAdQBwAD4ANQAuADAAMAA8AC8AdgBEAHUAcAA+ADwALwBkAHUAcAA+ADwAZAB1AHAAPgA8AG4ARAB1AHAAPgA3ADwALwBuAEQAdQBwAD4APABkAFYAZQBuAGMAPgAyADAAMQAxAC0AMQAwAC0AMgA2ADwALwBkAFYAZQBuAGMAPgA8AHYARAB1AHAAPgA1AC4AMAAwADwALwB2AEQAdQBwAD4APAAvAGQAdQBwAD4APABkAHUAcAA+ADwAbgBEAHUAcAA+ADgAPAAvAG4ARAB1AHAAPgA8AGQAVgBlAG4AYwA+ADIAMAAxADEALQAxADAALQAyADYAPAAvAGQAVgBlAG4AYwA+ADwAdgBEAHUAcAA+ADUALgAwADAAPAAvAHYARAB1AHAAPgA8AC8AZAB1AHAAPgA8AGQAdQBwAD4APABuAEQAdQBwAD4AOQA8AC8AbgBEAHUAcAA+ADwAZABWAGUAbgBjAD4AMgAwADEAMQAtADEAMAAtADIANgA8AC8AZABWAGUAbgBjAD4APAB2AEQAdQBwAD4ANQAuADAAMAA8AC8AdgBEAHUAcAA+ADwALwBkAHUAcAA+ADwAZAB1AHAAPgA8AG4ARAB1AHAAPgAxADAAPAAvAG4ARAB1AHAAPgA8AGQAVgBlAG4AYwA+ADIAMAAxADEALQAxADAALQAyADYAPAAvAGQAVgBlAG4AYwA+ADwAdgBEAHUAcAA+ADUALgAwADAAPAAvAHYARAB1AHAAPgA8AC8AZAB1AHAAPgA8AGQAdQBwAD4APABuAEQAdQBwAD4AMQAxADwALwBuAEQAdQBwAD4APABkAFYAZQBuAGMAPgAyADAAMQAxAC0AMQAwAC0AMgA2ADwALwBkAFYAZQBuAGMAPgA8AHYARAB1AHAAPgA1AC4AMAAwADwALwB2AEQAdQBwAD4APAAvAGQAdQBwAD4APABkAHUAcAA+ADwAbgBEAHUAcAA+ADEAMgA8AC8AbgBEAHUAcAA+ADwAZABWAGUAbgBjAD4AMgAwADEAMQAtADEAMAAtADIANgA8AC8AZABWAGUAbgBjAD4APAB2AEQAdQBwAD4ANQAuADAAMAA8AC8AdgBEAHUAcAA+ADwALwBkAHUAcAA+ADwALwBjAG8AYgByAD4APABpAG4AZgBBAGQAaQBjAD4APABpAG4AZgBBAGQARgBpAHMAYwBvAD4ASQBOAEYATwBSAE0AQQBDAE8ARQBTACAARABFACAASQBOAFQARQBSAEUAUwBTAEUAIABEAE8AIABGAEkAUwBDAE8APAAvAGkAbgBmAEEAZABGAGkAcwBjAG8APgA8AGkAbgBmAEMAcABsAD4ANwA4ADkAOAAwADgAMAA2ADQAMAA0ADEAMwAgADcAOAA5ADgAOQAwADQANAAxADgAMQA1ADAAIAA3ADgAOQA4ADEAMQA3ADkANgAwADAAMQA5ACAANwA4ADkAOAA5ADAANAA0ADEAOAAxADUAMAAgADcAOAA5ADgAMAA4ADAANgA0ADAANAAxADMAIAA3ADgAOQA4ADEAMQA3ADkANgAwADAAMQA5ACAANwA4ADkAMQAxADAANwAxADAAMQA2ADIAMQAgADcAOAA5ADEAMAA5ADEAMAAxADgAMAAxADEAIAA3ADgAOQA4ADkAMAA5ADQAOAA0ADEAMgA5ACAANwA4ADkAMQAwADIANAAxADEAMwA3ADgAMwAgADcAOAA5ADYAMwA4ADcAMAAxADYAMQAzADkAIAA3ADgAOQA2ADAANAAxADEANwAyADUAMwA5ACAANwA4ADkANgAyADEAMwAwADAAMAA2ADcANwAgADcAOAA5ADYAMgAxADMAMAAwADIAMAA5ADEAIAA3ADgAOQAxADAAMQAwADUAMAAzADAAMgA0ACAANAA5ADkAMgAgADIAMgA4ADQAIAAyADIAOAAyACAAMgAzADAAMAAgADIAMgA4ADYAIAAyADMAMgAwACAAMgAyADkANwAgADIAMwAxADQAIAAyADIAOAA3ADwALwBpAG4AZgBDAHAAbAA+ADwALwBpAG4AZgBBAGQAaQBjAD4APAAvAGkAbgBmAE4ARgBlAD4APABTAGkAZwBuAGEAdAB1AHIAZQAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwB3AHcAdwAuAHcAMwAuAG8AcgBnAC8AMgAwADAAMAAvADAAOQAvAHgAbQBsAGQAcwBpAGcAIwAiAD4APABTAGkAZwBuAGUAZABJAG4AZgBvAD4APABDAGEAbgBvAG4AaQBjAGEAbABpAHoAYQB0AGkAbwBuAE0AZQB0AGgAbwBkACAAQQBsAGcAbwByAGkAdABoAG0APQAiAGgAdAB0AHAAOgAvAC8AdwB3AHcALgB3ADMALgBvAHIAZwAvAFQAUgAvADIAMAAwADEALwBSAEUAQwAtAHgAbQBsAC0AYwAxADQAbgAtADIAMAAwADEAMAAzADEANQAiACAALwA+ADwAUwBpAGcAbgBhAHQAdQByAGUATQBlAHQAaABvAGQAIABBAGwAZwBvAHIAaQB0AGgAbQA9ACIAaAB0AHQAcAA6AC8ALwB3AHcAdwAuAHcAMwAuAG8AcgBnAC8AMgAwADAAMAAvADAAOQAvAHgAbQBsAGQAcwBpAGcAIwByAHMAYQAtAHMAaABhADEAIgAgAC8APgA8AFIAZQBmAGUAcgBlAG4AYwBlACAAVQBSAEkAPQAiACMATgBGAGUANAAzADEANAAwADEAMAA2ADMANQA0ADkANwA2ADAAMAAwADEANAA5ADUANQAzADIANAAwADAAMAAwADAANgAzADkAMQAxADAAMAAwADAAMAAxADEAMQAxACIAPgA8AFQAcgBhAG4AcwBmAG8AcgBtAHMAPgA8AFQAcgBhAG4AcwBmAG8AcgBtACAAQQBsAGcAbwByAGkAdABoAG0APQAiAGgAdAB0AHAAOgAvAC8AdwB3AHcALgB3ADMALgBvAHIAZwAvADIAMAAwADAALwAwADkALwB4AG0AbABkAHMAaQBnACMAZQBuAHYAZQBsAG8AcABlAGQALQBzAGkAZwBuAGEAdAB1AHIAZQAiACAALwA+ADwAVAByAGEAbgBzAGYAbwByAG0AIABBAGwAZwBvAHIAaQB0AGgAbQA9ACIAaAB0AHQAcAA6AC8ALwB3AHcAdwAuAHcAMwAuAG8AcgBnAC8AVABSAC8AMgAwADAAMQAvAFIARQBDAC0AeABtAGwALQBjADEANABuAC0AMgAwADAAMQAwADMAMQA1ACIAIAAvAD4APAAvAFQAcgBhAG4AcwBmAG8AcgBtAHMAPgA8AEQAaQBnAGUAcwB0AE0AZQB0AGgAbwBkACAAQQBsAGcAbwByAGkAdABoAG0APQAiAGgAdAB0AHAAOgAvAC8AdwB3AHcALgB3ADMALgBvAHIAZwAvADIAMAAwADAALwAwADkALwB4AG0AbABkAHMAaQBnACMAcwBoAGEAMQAiACAALwA+ADwARABpAGcAZQBzAHQAVgBhAGwAdQBlAD4AQwAyAHYALwBJADQANwBzAE4ATAAvADIAQQA4AHMAYgBZAHIAYQBGAGgAYgBpAE0ASAByAFUAPQA8AC8ARABpAGcAZQBzAHQAVgBhAGwAdQBlAD4APAAvAFIAZQBmAGUAcgBlAG4AYwBlAD4APAAvAFMAaQBnAG4AZQBkAEkAbgBmAG8APgA8AFMAaQBnAG4AYQB0AHUAcgBlAFYAYQBsAHUAZQA+AEcASABqAFgAZwBqAHkATgBxAGIATwByAGYAYgB5AFcAbQB0ADQAOAB5AGsAdQBXAFEAUgB4AFAAOQBsAGgASQBvAGwAaAAwAFIAbAB0AFcAUQBVAGcATQArAFUAOQBYAHUAcAA2ADYANABaAHAAaAB2AFEAYQB1AHMAUgBmAEQARwBxAHIAUgBLAEwAcgBiAHgATwB2AGQAdwAvAGEAUQBUADMAUQBPAFcAKwBoAG4ATgBaAG0ATwB0AFQAMAB4AFUAUABaAEsARwBnAHAASABXAFcAVQBjAG8ASABoAFYAYgBlAFIAdABBAE8ANABEAGgAagByAE0AVwBQAEYAUAA0AHkAWgB2AFoAMAA0AFAAdwBzAFMAYgBiAEIAQwBjAG0AOQBWAFUAWgA0AHEARAAyAGIAMAB1ADYAZwByAEoARwAvAGcASgBnAHkASQB0AEgAeAAzADYATQB1AFcAcQBFAHEAagAvAFUAcQBGAG8AcABSAHUANQBsAE0AZQBJAHUANgBSAFIARABrAE8ATwBBAEEASQBkAEwAUwBhAG8ANQBOAGQAUgB2AFoAeAAyAFkAYgB6ADIANQBnAGgAbwB3AFQAUABvAFUAaQB3AFEAVAAzAGcAbgBpACsAdABGADgAYgBBAGsAWABEADQAZQAzAEkALwBPAEUAcAA5ADEAUwA0AFEAbwBBAHoAUAA0ADkAcwBoAG8AWgB5AGUAOQAyAGsAaQBoAFIAUgBwAFMAdQA4AHYAOAB0AFIAeABEAEQAUwBDADAAQgBuAFkASwA5AEMAUgBLAFkARgBDADYAdABOADcAZwArAGQAQwBZAG8AbQBHAE0ARABTADcAbwBTAFQAWQA0AHYAagA3AEkAUwBpADUAdQBmAHgANABFAFQASQBFAHoAegBnAD0APQA8AC8AUwBpAGcAbgBhAHQAdQByAGUAVgBhAGwAdQBlAD4APABLAGUAeQBJAG4AZgBvAD4APABYADUAMAA5AEQAYQB0AGEAPgA8AFgANQAwADkAQwBlAHIAdABpAGYAaQBjAGEAdABlAD4ATQBJAEkASABJAGoAQwBDAEIAUQBxAGcAQQB3AEkAQgBBAGcASQBJAFQAZgBKAHIAdABiAGgAdwBGADkAcwB3AEQAUQBZAEoASwBvAFoASQBoAHYAYwBOAEEAUQBFAEwAQgBRAEEAdwBYAFQARQBMAE0AQQBrAEcAQQAxAFUARQBCAGgATQBDAFEAbABJAHgARQB6AEEAUgBCAGcATgBWAEIAQQBvAE0AQwBrAGwARABVAEMAMQBDAGMAbQBGAHoAYQBXAHcAeABJAEQAQQBlAEIAZwBOAFYAQgBBAHMATQBGADAATgBoAGEAWABoAGgASQBFAFYAagBiADIANQB2AGIAVwBsAGoAWQBTAEIARwBaAFcAUgBsAGMAbQBGAHMATQBSAGMAdwBGAFEAWQBEAFYAUQBRAEQARABBADUAQgBRAHkAQgBEAFEAVQBsAFkAUQBTAEIAUQBTAGkAQgAyAE0AagBBAGUARgB3ADAAeABNAHoAQQAwAE0AVABjAHgATgBEAEUANABOAEQAaABhAEYAdwAwAHgATgBEAEEAMABNAFQAYwB4AE4ARABFADQATgBEAGgAYQBNAEkARwBmAE0AUQBzAHcAQwBRAFkARABWAFEAUQBHAEUAdwBKAEMAVQBqAEUAVABNAEIARQBHAEEAMQBVAEUAQwBnAHcASwBTAFUATgBRAEwAVQBKAHkAWQBYAE4AcABiAEQARQBnAE0AQgA0AEcAQQAxAFUARQBDAHcAdwBYAFEAMgBGAHAAZQBHAEUAZwBSAFcATgB2AGIAbQA5AHQAYQBXAE4AaABJAEUAWgBsAFoARwBWAHkAWQBXAHcAeABGAHoAQQBWAEIAZwBOAFYAQgBBAHMATQBEAGsARgBEAEkARQBOAEIAUwBWAGgAQgBJAEYAQgBLAEkASABZAHkATQBVAEEAdwBQAGcAWQBEAFYAUQBRAEQARABEAGQATgBTAFUAZABTAFEAVgBSAEYASQBFAE4AUABUAFYAQgBCAFQAbABrAGcAVQAwAGwAVABWAEUAVgBOAFEAVgBNAGcAUgBFAFUAZwBTAFUANQBHAFQAMQBKAE4AUQBVAE4AQgBUAHkAQgBNAFYARQBSAEIATwBqAEEAdwBNAEQAZwB3AE4AagBFAHoATQBEAEEAMABNAEkASQBCAEkAagBBAE4AQgBnAGsAcQBoAGsAaQBHADkAdwAwAEIAQQBRAEUARgBBAEEATwBDAEEAUQA4AEEATQBJAEkAQgBDAGcASwBDAEEAUQBFAEEAaAArAGUAdwBGAE0AVABHAFkAZwAxAHcAOABZAEwAbQBCAGoAYQAzAGQAMgBrAGQAWgBXAFkAZABqAHcAMwA3AHgAcwBoAFIAZwAwAHoAdQBMADkASgBKAEcAbgBvAFEAZgB3AGYAeQA5AFUAcwBCAHoAMAB0AEwARgBmAGgAeABSAGkANABzAG0AbgBFAHIAOABoADAAeQBoAEoASgBpAHgAdwB0AC8AQgB4AEcAZgB5AEQAcQA2AGgAWgBnAEgAZAA1ADEAdQBiADUALwBQAEcAaQBBAHcAZAB2AFkAQQBkAHYAbABxAHgAcwBsAHIAZAB5AEoARQBYAFYAYgBCAGEAOABDAFQAcABLAEsAZgA1AG4AZAArAHEAQQBhAFYAZwBwAFoARQB2AE0AaABGAFAAZgA0AG0ATwB3ADMAWAA2AEwAaABOAFYASgBHADAAcgB6AGQAdQB0AHYAbQByAG8AdQBhAEYAUgBjAG8AcgBpAFgAMABiAFUANgBzAGkAcABHAEYAVwBaAG0AcwBHADIAegBjAFQANQBDAGsANwBNAG8AbQAwAE0AYwBlAGQAZgBDADYAVQBTAHYAQwArAFUARgBaAEEAbgBiAG8ALwB1AFkAQgBiAHcARQArAG8ASwBiAFkALwBPAHoAdQAzAG8AZgBDAFYAOQBTAHUAWgBMAEQAWgA0AHkAMQBKAFMAdwA2AHoAMQBaAEsAUABDAFIAawByADkAegBzADAARwBQAHYAWQBFAHcANgAxAGUAeQBHAHcAagBTAHIAQQBZAHIANgBDAG8AQQBkAEsAcgBBADIANgBqAE4ALwAyAGcAcAAwAGIAWAAvADIAWQBEAEcAYQBLAEEAVAAwAG0ASABFAFQAUwBHAE0AUwB1AE4AagAzAFAAYQBYAHcASQBEAEEAUQBBAEIAbwA0AEkAQwBvAFQAQwBDAEEAcAAwAHcARABnAFkARABWAFIAMABQAEEAUQBIAC8AQgBBAFEARABBAGcAWABnAE0AQwBrAEcAQQAxAFUAZABKAFEAUQBpAE0AQwBBAEcAQwBDAHMARwBBAFEAVQBGAEIAdwBNAEMAQgBnAGcAcgBCAGcARQBGAEIAUQBjAEQAQgBBAFkASwBLAHcAWQBCAEIAQQBHAEMATgB4AFEAQwBBAGoAQQBkAEIAZwBOAFYASABRADQARQBGAGcAUQBVAEEAYgBhAEMAQgBzAGMAYwBCAGgAZQBjAEEAVwArAEwARQArAHkAVwBEAFEAZwBTAHoAagAwAHcASAB3AFkARABWAFIAMABqAEIAQgBnAHcARgBvAEEAVQBUADAAMABOAEEAWgB4AHEAYQBkAHQAdwBDAGEAVABlAE0ANgA3ADIAZgBKAEsAZQBOAGMASQB3AGcAYQBNAEcAQQAxAFUAZABFAFEAUwBCAG0AegBDAEIAbQBLAEEAWABCAGcAVgBnAFQAQQBFAEQAQgA2AEEATwBCAEEAdwB3AE0ARABBAHcATQBEAEEAdwBNAEQAQQB3AE0ARABDAGcAUABRAFkARgBZAEUAdwBCAEEAdwBTAGcATgBBAFEAeQBNAEQARQB3AE8AVABFADUATwBEAEkAdwBNAEQAQQA0AE0ARABZAHgATQB6AEEAdwBOAEQAQQB3AE0ARABBAHcATQBEAEEAdwBNAEQAQQB3AE0ARABBAHcATQBEAEEAMQBNAEQAVQAwAE0AagBNAHgATgBUAFkAMwBVADEATgBRAFUAbABPAGcARwBRAFkARgBZAEUAdwBCAEEAdwBPAGcARQBBAFEATwBNAEQAWQB6AE4AVABRADUATgB6AFkAdwBNAEQAQQB4AE4ARABtAGcASQB3AFkARgBZAEUAdwBCAEEAdwBLAGcARwBnAFEAWQBSADAAeABCAFYAVQBKAEYAVQBpAEIARABUAEUARgBWAFIARQBsAFMASQBGAGQARgBSAEUAUgBKAFIAMABWAE8ATQBHAFkARwBBADEAVQBkAEkAQQBSAGYATQBGADAAdwBXAHcAWQBHAFkARQB3AEIAQQBnAEUASgBNAEYARQB3AFQAdwBZAEkASwB3AFkAQgBCAFEAVQBIAEEAZwBFAFcAUQAyAGgAMABkAEgAQQA2AEwAeQA5AGoAWgBYAEoAMABhAFcAWgBwAFkAMgBGAGsAYgAyAFIAcABaADIAbAAwAFkAVwB3AHUAWQAyAEYAcABlAEcARQB1AFoAMgA5ADIATABtAEoAeQBMADIAUgB2AFkAMwBWAHQAWgBXADUAMABiADMATQB2AFoASABCAGoAWQBXAE0AdABZADIARgBwAGUARwBGAHcAYQBpADUAdwBaAEcAWQB3AGcAYgBrAEcAQQAxAFUAZABIAHcAUwBCAHMAVABDAEIAcgBqAEEAdABvAEMAdQBnAEsAWQBZAG4AYQBIAFIAMABjAEQAbwB2AEwAMgB4AGoAYwBpADUAagBZAFcAbAA0AFkAUwA1AG4AYgAzAFkAdQBZAG4ASQB2AFkAVwBOAGoAWQBXAGwANABZAFgAQgBxAGQAagBJAHUAWQAzAEoAcwBNAEMANgBnAEwASwBBAHEAaABpAGgAbwBkAEgAUgB3AE8AaQA4AHYAYgBHAE4AeQBNAGkANQBqAFkAVwBsADQAWQBTADUAbgBiADMAWQB1AFkAbgBJAHYAWQBXAE4AagBZAFcAbAA0AFkAWABCAHEAZABqAEkAdQBZADMASgBzAE0ARQAyAGcAUwA2AEIASgBoAGsAZABvAGQASABSAHcATwBpADgAdgBjAG0AVgB3AGIAMwBOAHAAZABHADkAeQBhAFcAOAB1AGEAVwBOAHcAWQBuAEoAaABjADIAbABzAEwAbQBkAHYAZABpADUAaQBjAGkAOQBzAFkAMwBJAHYAUQAwAEYASgBXAEUARQB2AFEAVQBOAEQAUQBVAGwAWQBRAFYAQgBLAEwAMgBGAGoAWQAyAEYAcABlAEcARgB3AGEAbgBZAHkATABtAE4AeQBiAEQAQgBXAEIAZwBnAHIAQgBnAEUARgBCAFEAYwBCAEEAUQBSAEsATQBFAGcAdwBSAGcAWQBJAEsAdwBZAEIAQgBRAFUASABNAEEASwBHAE8AbQBoADAAZABIAEEANgBMAHkAOQBqAFoAWABKADAAYQBXAFoAcABZADIARgBrAGIAMgBSAHAAWgAyAGwAMABZAFcAdwB1AFkAMgBGAHAAZQBHAEUAdQBaADIAOQAyAEwAbQBKAHkATAAyAEYAcABZAFMAOQBoAFkAMgBOAGgAYQBYAGgAaABjAEcAcAAyAE0AaQA1AHcATgAyAEkAdwBEAFEAWQBKAEsAbwBaAEkAaAB2AGMATgBBAFEARQBMAEIAUQBBAEQAZwBnAEkAQgBBAEEAQQBiAGgASwBxAHUARABkAGcAdgBjAEIARAB1AE4AeQBxAHMAWgBFAGoAUwBwAFcASgB1AHUAQQB0AFYAKwBXADQAUQBXADIAeAA2AC8AbwBiAGQAcABIAEkAcAA0AEIATwBjAEQAYQB2AG4AVQBBADUAVABEAGQAQQBaAGEAOQBQAHUAMwA0AGkAegBJAEkASAA5ACsATQBmAGMARwBGADYAZgBUAE0AMABLAFcAVgArAFQAQwBLAFUAeQBsADMAMgBwAFEAcABmADIAUQBiAHcAVwBKAC8ASQBnADUAdQBEAFYASQB2AHkAZABuAE0AUgBTAHoATQBpAFgAbABBAFcASgBKAEsAKwBFAEYAVwA2AGUATgBTAHgAeQAxAG8AbwBQAGMANwA1AEMAZQB6AGQAUwBqAE0ANQBYAGgAVgBRAHIAbgBmADQAWgBzAFkATwBkAFMATQAyAG8AVgBUAE4AagBxACsAbwB3AFAARABNAEYAagBoAHoANgBwAFcARgAvAGcAMgBpAEIASwBYAFkAWgBYAGIAKwBJAFcAWQBzAGcAaABaAHkAOABsAHAAbQBrADUAcABCAHYAbABzAGMAdQA0AGMAMgB1ADUAYwBBAGEAWgBRAHkAZgAxAE8AbgBvAGkAUgA1ADQAdAB0AHQANwBsAGwAUQBqADUAbgBLAGgARgBFADQATgBOAEQAQwA2AGgASQBKAE0ASAArAE4AUgB6AEoAdQB4ACsAdABjAHcAVQBzAC8AaQAzAEgAaAArAG8AZABCACsAcAB5ADQAOQB6AHgAcgBFAG8AZAB6ADEAcABqAGkAeABZAEMAZgBMAEQAQwBzAG4AcgB3AFkAVgB3ACsAYQBlAGUAYQB1AEIARABPAGMAZAArAGsAVgB4ADIAdABSADgAMABuAC8ANQA2AE0AaABsAEQAdAA3AHEAMABBAGkAbwBZAEQAOQBNAHQAdwA4AC8AZgBFAFgAUQBsAFIAegA3AGkAcQBMAHoAZwBnAHEAYwBMAGEAdwBHADQAdABjADEAVQBwAHIASwBEAE0AYwBoAGsAeQBDAEwAMAB5AGEASwB5AEYAVABlAHAAVAB5AFgAVwBrAG0AWABxAGEAcwBkAFMASwBiADMAcQBrAG4AMABHAFUARgBFADAAZgBZAHkAUQBCAG0ASwBEADAALwBHAFoATABoAEgAUgBOAGUATgBJAG8ATQB0AGUATQBpAHkAbwBrAGwAMQByADIAQwB4AFQAZQBGAG8AeQBYAE4AMQBWAGkAagBxAG0AaQB2AE4ASABXAGMAWQB6AGoATQA2AEIARQBSAEYARwB2AHgAWQBEADAAdQBXAEUAUwBHAHAAWAB5AE8AYQB1AGIATQA3ADUAZABPADAAdABnAG4AUgBQADgAZAB6AGsALwB6AEUAMQA1AFoAOABnAGcAUAA0ADYAcABpAFAAbwByAFMARAAyAGwAbwA2AHEAQwA1AHUAaQBhAHoAawBEAFgAMgAzAFMAeQBGAHUAdwBXAHgAZAB1AE4ATgBYAE0AUABEAGQAMwBlAEYALwB6AFUAcQBpAFEAdwAwAFcAcwBHADMAOAAwAFIATABwAEMAdAAxAGMAWgBQADcATwBCAG4AWAA1ADYAUwBmADAASABZAG8ASgBPAHQASQB1AGIANwBaAGsAZABDAEkAOABBADQAdAA1AGUAbABvAC8AVwBBAGQAQgBUAEUAegBUAHkAbQBtADEAQQBGAG4ARABRADMAdwAvAFcAQgBZAGsAVgA0AE4AZwBlAGwATwByADIASABlADEAUQBzAG8AMQA8AC8AWAA1ADAAOQBDAGUAcgB0AGkAZgBpAGMAYQB0AGUAPgA8AC8AWAA1ADAAOQBEAGEAdABhAD4APAAvAEsAZQB5AEkAbgBmAG8APgA8AC8AUwBpAGcAbgBhAHQAdQByAGUAPgA8AC8ATgBGAGUAPgA8AHAAcgBvAHQATgBGAGUAIAB2AGUAcgBzAGEAbwA9ACIAMwAuADEAMAAiAD4APABpAG4AZgBQAHIAbwB0ACAASQBkAD0AIgBJAEQAMQA0ADMAMQA0ADAAMAAwADAAMAA2ADIAMgA3ADUAIgA+ADwAdABwAEEAbQBiAD4AMgA8AC8AdABwAEEAbQBiAD4APAB2AGUAcgBBAHAAbABpAGMAPgBSAFMAMgAwADEAMwAxADEAMgA3ADEANAAyADkAMAA4ADwALwB2AGUAcgBBAHAAbABpAGMAPgA8AGMAaABOAEYAZQA+ADQAMwAxADQAMAAxADAANgAzADUANAA5ADcANgAwADAAMAAxADQAOQA1ADUAMwAyADQAMAAwADAAMAAwADYAMwA5ADEAMQAwADAAMAAwADAAMQAxADEAMQA8AC8AYwBoAE4ARgBlAD4APABkAGgAUgBlAGMAYgB0AG8APgAyADAAMQA0AC0AMAAxAC0AMQA3AFQAMQAxADoANQAwADoANQAxAC0AMAAyADoAMAAwADwALwBkAGgAUgBlAGMAYgB0AG8APgA8AG4AUAByAG8AdAA+ADEANAAzADEANAAwADAAMAAwADAANgAyADIANwA1ADwALwBuAFAAcgBvAHQAPgA8AGQAaQBnAFYAYQBsAD4AQwAyAHYALwBJADQANwBzAE4ATAAvADIAQQA4AHMAYgBZAHIAYQBGAGgAYgBpAE0ASAByAFUAPQA8AC8AZABpAGcAVgBhAGwAPgA8AGMAUwB0AGEAdAA+ADEAMAAwADwALwBjAFMAdABhAHQAPgA8AHgATQBvAHQAaQB2AG8APgBBAHUAdABvAHIAaQB6AGEAZABvACAAbwAgAHUAcwBvACAAZABhACAATgBGAC0AZQA8AC8AeABNAG8AdABpAHYAbwA+ADwALwBpAG4AZgBQAHIAbwB0AD4APAAvAHAAcgBvAHQATgBGAGUAPgA8AC8AbgBmAGUAUAByAG8AYwA+AA==</DocXML>
                                            <DocXMLLink>http://homolog.invoicy.com.br/hnuc002.aspx?k6rMlBDjfK%2fjBRL3Y7yJxdKTrLLvOCxS%2fAKnGLN0Uo8%3d,0</DocXMLLink>
                                            <DocPDF>pdfEMbase64</DocPDF>
                                            <DocPDFLink />
                                            <Resumo>
                                                <DocDataEmissao>2014-01-17T11:50:00</DocDataEmissao>
                                                <DocNomeEmitente>MIGRATE COMPANY SISTEMAS DE INFORMACAO</DocNomeEmitente>
                                                <DocCNPJDestinatario>99999999000191</DocCNPJDestinatario>
                                                <DocNomeDestinatario>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</DocNomeDestinatario>
                                                <DocVlrTotal>100</DocVlrTotal>
                                            </Resumo>
                                            <Eventos />
                                        </Documento>
                                    ]]>
                                </Documento>
                            </DocumentosItem>
                        </Documentos>
                    </MensagemItem>
                </Mensagem>
            </Invoicyretorno>
        </recepcao.ExecuteResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

*/ 

//session_start();
if (empty($_COOKIE['logado'])) {
    print "<script>location.href = '../../login.php?entre=false';</script>";
}

include("../../conn.php");
include("../../wfunction.php");
include("../../classes/BotoesClass.php");
include("../../classes/NFeClass.php");
include("../../classes/BancoClass.php");
include("../../classes/global.php");

$usuario = carregaUsuario();
$id_regiao = $usuario['id_regiao'];

//PREPARA VARIAVEIS PARA FUNCIONAMENTO DO CABEÇALHO (TROCA DE MASTER E DE REGIÕES)
$dadosHeader = montaCabecalhoNovo(getRegioes(), getMasters(), $usuario, __FILE__);

// seta um valor para variável aba. usado para definir a aba aberta.
$aba = (isset($_REQUEST['aba'])) ? $_REQUEST['aba'] : 'cadastrar';

$projeto1 = montaSelect(array("-1" => "« Selecione a Região »"), $projetoR, "id='projeto1' name='projeto' class='form-control validate[required,custom[select]]' data-for='prestador1'");
$projeto2 = montaSelect(array("-1" => "« Selecione a Região »"), $projetoR, "id='projeto2' name='projeto' class='form-control validate[required,custom[select]]' data-for='prestador2'");
$projeto3 = montaSelect(array("-1" => "« Selecione a Região »"), $projetoR, "id='projeto3' name='projeto' class='form-control validate[required,custom[select]]' data-for='prestador3'");

$global = new GlobalClass();

$sqlcfop = mysql_query("SELECT * FROM nfe_cfop ORDER BY id_cfop");

function checkSel($Selecao1, $Selecao2) {
    return ($Selecao1 == $Selecao2) ? 'active' : '';
}
function checkAba($aba1, $aba2) {
    return ($aba1 == $aba2) ? 'active' : '';
}

$breadcrumb_config = array("nivel" => "../../", "key_btn" => "35", "area" => "Gestão de Compras e Contratos", "ativo" => "NFe", "id_form" => "form1");
?>
<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="iso-8859-1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>:: Intranet :: Gestão NFe</title>
        <link rel="shortcut icon" href="../../favicon.png">
        <!-- Bootstrap -->        
        <link href="../../css/validationEngine.jquery.css" rel="stylesheet" type="text/css">
        <link href="../../resources/css/bootstrap.css" rel="stylesheet" media="screen">
        <link href="../../resources/css/bootstrap-theme.css" rel="stylesheet" media="screen">
        <link href="../../resources/css/bootstrap-dialog.min.css" rel="stylesheet" media="screen">
        <link href="../../resources/css/bootstrap-compras.css" rel="stylesheet" media="screen">
        <link href="../../resources/css/ui-datepicker-theme.css" rel="stylesheet" media="screen">
        <link href="../../resources/css/ui-autocomplete-theme.css" rel="stylesheet" media="screen">
        <link href="../../resources/css/main.css" rel="stylesheet" media="screen">
        <link href="../../resources/css/font-awesome.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <?php include("../../template/navbar_default.php"); ?> 
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="page-header box-compras-header">
                        <h2><span class="glyphicon glyphicon-shopping-cart"></span> - Gestão de Compras e Contratos <small>- Notas Fiscais</small></h2>
                    </div>
                    <!--resposta de algum metodo realizado-->
                    <?php echo $global->getResposta($_SESSION['MESSAGE_TYPE'], $_SESSION['MESSAGE']); ?>                                
                    <!--<div role="tabpanel">-->
                    <div class="bs-component" role="tablist">
                        <div id="myTabContent1" class="tab-content">
                            <div role="tabpanel" class="tab-pane fade in active" id="sel-nfe">
                                <?php include '';?>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
            <?php include_once '../../template/footer.php'; ?>
        </div>
        <script src="../../js/jquery-1.10.2.min.js"></script>
        <script src="../../js/jquery-ui-1.9.2.custom.min.js"></script>
        <script src="../../resources/js/bootstrap.min.js"></script>
        <script src="../../resources/js/bootstrap-dialog.min.js"></script>
        <script src="../../resources/js/main.js"></script>
        <script src="../../js/global.js"></script>
        <script src="../../js/jquery.maskedinput-1.3.1.js"></script>
        <script src="../../resources/js/financeiro/saida.js"></script>
        <script src="../../js/jquery.validationEngine-2.6.js"></script>
        <script src="../../js/jquery.validationEngine-pt_BR-2.6.js"></script>
        <script src="../../js/jquery.maskMoney_3.0.2.js"></script>
        <script src="../../js/jquery.form.js" type="text/javascript"></script>
        <script src="../../resources/js/bootstrap-filestyle.min.js" type="text/javascript"></script>
        <script src="form_NFe.js" type="text/javascript"></script><!-- depois apontar para aresourse -->
        <style>
            .legends{
                font-size: 0.9em;
                color: silver;
            }
        </style>
    </body>
</html>