<?php
header('Content-Type: text/html; charset=ISO-8859-1');

include('../../conn.php');

$qry = array(
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MONIQUE CAVALCANTE VILAS BOAS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ELIANAI OLIVEIRA DOS SANTOS MENDES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ELIANAI OLIVEIRA DOS SANTOS MENDES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%GEISA COSTA DA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%GEISA COSTA DA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SILVANA NASCIMENTO DA LUZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SILVANA NASCIMENTO DA LUZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANDREA CRISTINA FERREIRA CHAGAS DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANDREA CRISTINA FERREIRA CHAGAS DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%PATRICIA SANTOS SOARES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%PATRICIA SANTOS SOARES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FRANCISCA DAS CHAGAS MAGALHAES CARVALHO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FRANCISCA DAS CHAGAS MAGALHAES CARVALHO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ELIANAI OLIVEIRA DOS SANTOS MENDES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ELIANAI OLIVEIRA DOS SANTOS MENDES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%GEISA COSTA DA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%GEISA COSTA DA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SILVANA NASCIMENTO DA LUZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SILVANA NASCIMENTO DA LUZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANDREA CRISTINA FERREIRA CHAGAS DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANDREA CRISTINA FERREIRA CHAGAS DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%PATRICIA SANTOS SOARES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%PATRICIA SANTOS SOARES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FRANCISCA DAS CHAGAS MAGALHAES CARVALHO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FRANCISCA DAS CHAGAS MAGALHAES CARVALHO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ELIANAI OLIVEIRA DOS SANTOS MENDES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ELIANAI OLIVEIRA DOS SANTOS MENDES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%GEISA COSTA DA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%GEISA COSTA DA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SILVANA NASCIMENTO DA LUZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SILVANA NASCIMENTO DA LUZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANDREA CRISTINA FERREIRA CHAGAS DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANDREA CRISTINA FERREIRA CHAGAS DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%PATRICIA SANTOS SOARES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%PATRICIA SANTOS SOARES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FRANCISCA DAS CHAGAS MAGALHAES CARVALHO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FRANCISCA DAS CHAGAS MAGALHAES CARVALHO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ELIANAI OLIVEIRA DOS SANTOS MENDES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ELIANAI OLIVEIRA DOS SANTOS MENDES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%GEISA COSTA DA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%GEISA COSTA DA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SILVANA NASCIMENTO DA LUZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SILVANA NASCIMENTO DA LUZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANDREA CRISTINA FERREIRA CHAGAS DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANDREA CRISTINA FERREIRA CHAGAS DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%PATRICIA SANTOS SOARES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%PATRICIA SANTOS SOARES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FRANCISCA DAS CHAGAS MAGALHAES CARVALHO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FRANCISCA DAS CHAGAS MAGALHAES CARVALHO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ELIANAI OLIVEIRA DOS SANTOS MENDES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ELIANAI OLIVEIRA DOS SANTOS MENDES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%GEISA COSTA DA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%GEISA COSTA DA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SILVANA NASCIMENTO DA LUZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SILVANA NASCIMENTO DA LUZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANDREA CRISTINA FERREIRA CHAGAS DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANDREA CRISTINA FERREIRA CHAGAS DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%PATRICIA SANTOS SOARES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%PATRICIA SANTOS SOARES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FRANCISCA DAS CHAGAS MAGALHAES CARVALHO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FRANCISCA DAS CHAGAS MAGALHAES CARVALHO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DUDA PEREIRA DE MORAES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROSIMAR JACINTO DA COSTA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ZULEICA BARBOSA CAMARGO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MIRALDA LUIZ DA SILVA TOBÍAS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DAIANA DE PAULA SANTIAGO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MONICA DA SILVA BARBOSA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ALUIMARIA DE AMORIM SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIA ASSUNÇÃO DA S. OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROSIMAR JACINTO DA COSTA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MIRALDA LUIZ DA SILVA TOBÍAS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ALUIMARIA DE AMORIM SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MONICA DA SILVA BARBOSA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ALUIMARIA DE AMORIM SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIA ASSUNÇÃO DA S. OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROSIMAR JACINTO DA COSTA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MIRALDA LUIZ DA SILVA TOBÍAS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DAIANA DE PAULA SANTIAGO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MONICA DA SILVA BARBOSA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ALUIMARIA DE AMORIM SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIA ASSUNÇÃO DA S. OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROSIMAR JACINTO DA COSTA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MIRALDA LUIZ DA SILVA TOBÍAS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DAIANA DE PAULA SANTIAGO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MONICA DA SILVA BARBOSA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ALUIMARIA DE AMORIM SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIA ASSUNÇÃO DA S. OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROSIMAR JACINTO DA COSTA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MIRALDA LUIZ DA SILVA TOBÍAS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DAIANA DE PAULA SANTIAGO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MONICA DA SILVA BARBOSA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ALUIMARIA DE AMORIM SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIA ASSUNÇÃO DA S. OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%IRANETE GONCALVES DA MOTTA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIA SHIRLEY DA CONCEIÇÃO RAMOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ITAMARA APARECIDA LOURENÇO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%JORGE EDUARDO RODRIGUES BATISTA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%VALDIANA DA SILVA ROCHA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%THAIS PREIOSA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%IRANETE GONCALVES DA MOTTA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIA SHIRLEY DA CONCEIÇÃO RAMOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%JANAINA DE QUEIROZ PEREIRA VIRTUOSO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%THAIS PREIOSA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%JANAINA DE QUEIROZ PEREIRA VIRTUOSO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%JORGE EDUARDO RODRIGUES BATISTA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROMILDO PEGADA ARRUDA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%CARINA EVANGELISTA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%IRANETE GONCALVES DA MOTTA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIA SHIRLEY DA CONCEIÇÃO RAMOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%JANAINA DE QUEIROZ PEREIRA VIRTUOSO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%THAIS PREIOSA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%JANAINA DE QUEIROZ PEREIRA VIRTUOSO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%JORGE EDUARDO RODRIGUES BATISTA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROMILDO PEGADA ARRUDA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%CARINA EVANGELISTA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIA SHIRLEY DA CONCEIÇÃO RAMOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%JANAINA DE QUEIROZ PEREIRA VIRTUOSO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%THAIS PREIOSA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%JANAINA DE QUEIROZ PEREIRA VIRTUOSO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%JORGE EDUARDO RODRIGUES BATISTA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROMILDO PEGADA ARRUDA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%CARINA EVANGELISTA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%IRANETE GONCALVES DA MOTTA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIA SHIRLEY DA CONCEIÇÃO RAMOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%JANAINA DE QUEIROZ PEREIRA VIRTUOSO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%THAIS PREIOSA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%JANAINA DE QUEIROZ PEREIRA VIRTUOSO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%JORGE EDUARDO RODRIGUES BATISTA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROMILDO PEGADA ARRUDA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%CARINA EVANGELISTA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%KAROLINE WERNER DA SILVA MATTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LIVIA BELO DA FONSECA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LIVIA BELO DA FONSECA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DANIELE CORLETT DA COSTA GOMES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DANIELE CORLETT DA COSTA GOMES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%IVANA APARECIDA SILVA RAMOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%GABRIELA DA COSTA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FERNANDA TAVARES DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FERNANDA TAVARES DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LAURINETE SETORIO SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LAURINETE SETORIO SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%KAROLINE WERNER DA SILVA MATTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%KAROLINE WERNER DA SILVA MATTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LIVIA BELO DA FONSECA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LIVIA BELO DA FONSECA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DANIELE CORLETT DA COSTA GOMES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DANIELE CORLETT DA COSTA GOMES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%IVANA APARECIDA SILVA RAMOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%IVANA APARECIDA SILVA RAMOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FERNANDA TAVARES DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FERNANDA TAVARES DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LAURINETE SETORIO SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LAURINETE SETORIO SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%KAROLINE WERNER DA SILVA MATTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARCIA CRISTINA DE CARVALHO MIRANDA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LIVIA BELO DA FONSECA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LIVIA BELO DA FONSECA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DANIELE CORLETT DA COSTA GOMES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DANIELE CORLETT DA COSTA GOMES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%IVANA APARECIDA SILVA RAMOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%IVANA APARECIDA SILVA RAMOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FERNANDA TAVARES DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FERNANDA TAVARES DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LAURINETE SETORIO SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LAURINETE SETORIO SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%KAROLINE WERNER DA SILVA MATTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%KAROLINE WERNER DA SILVA MATTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LIVIA BELO DA FONSECA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LIVIA BELO DA FONSECA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DANIELE CORLETT DA COSTA GOMES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DANIELE CORLETT DA COSTA GOMES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%IVANA APARECIDA SILVA RAMOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%IVANA APARECIDA SILVA RAMOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FERNANDA TAVARES DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FERNANDA TAVARES DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LAURINETE SETORIO SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LAURINETE SETORIO SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%KAROLINE WERNER DA SILVA MATTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%KAROLINE WERNER DA SILVA MATTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LIVIA BELO DA FONSECA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LIVIA BELO DA FONSECA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DANIELE CORLETT DA COSTA GOMES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%DANIELE CORLETT DA COSTA GOMES%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%IVANA APARECIDA SILVA RAMOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%IVANA APARECIDA SILVA RAMOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FERNANDA TAVARES DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FERNANDA TAVARES DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LAURINETE SETORIO SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%LAURINETE SETORIO SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%KAROLINE WERNER DA SILVA MATTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%KAROLINE WERNER DA SILVA MATTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%JOCINEIA GUIMARÃES DOS SANTOS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANA LUCIA SENRA SOUZA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANA LUCIA SENRA SOUZA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANA LUCIA SENRA SOUZA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANA LUCIA SENRA SOUZA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ANA LUCIA SENRA SOUZA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%RODRIGO DE ARAUJO SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%TIAGO PACHECO DE CARVALHO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%VIVIANE REGINA GONÇALVES DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%VANILSON FELIPPE DINIZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FABIANE SOARES MOREIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%VIVIANE REGINA GONÇALVES DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%VANILSON FELIPPE DINIZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%VIVIANE REGINA GONÇALVES DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%VANILSON FELIPPE DINIZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FABIANE SOARES MOREIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%VIVIANE REGINA GONÇALVES DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%VANILSON FELIPPE DINIZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%TIAGO PACHECO DE CARVALHO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%VIVIANE REGINA GONÇALVES DE OLIVEIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%VANILSON FELIPPE DINIZ%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%FABIANE SOARES MOREIRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIA ANTONIA COSTA BESERRA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SUELEN VARELA DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROSANGELA ROCHA SILVA CORDEIRO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%TATIANA DOS SANTOS LACERDA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARY ANE DE MELO MARTINS%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SUELEN VARELA DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROSANGELA ROCHA SILVA CORDEIRO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%TATIANA DOS SANTOS LACERDA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROSIMERI CABRAL%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIANA TAVARES SILI%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SUELEN VARELA DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROSANGELA ROCHA SILVA CORDEIRO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%TATIANA DOS SANTOS LACERDA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROSIMERI CABRAL%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIANA TAVARES SILI%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SUELEN VARELA DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROSANGELA ROCHA SILVA CORDEIRO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%TATIANA DOS SANTOS LACERDA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROSIMERI CABRAL%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIANA TAVARES SILI%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%SUELEN VARELA DA SILVA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROSANGELA ROCHA SILVA CORDEIRO%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%TATIANA DOS SANTOS LACERDA%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%ROSIMERI CABRAL%';",
"SELECT CONCAT('UPDATE rh_clt SET id_centro_custo = 35 WHERE id_clt = ', id_clt,';') AS upd FROM rh_clt WHERE nome LIKE '%MARIANA TAVARES SILI%';"
);

foreach($qry as $valor){
    $A = mysql_query($valor);
    
    if(!empty(mysql_result($A, 0))){
        mysql_query(mysql_result($A, 0));
    }
}
?>